//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecieptLine
    {
        public int Id { get; set; }
        public int count { get; set; }
        public int product_id { get; set; }
        public int reciept_id { get; set; }
        public int count_sum { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Reciept Reciept { get; set; }
    }
}
